### ISSUE TITLE
Why map to the H37Rv reference genome twice using minimap?

### ISSUE THREAD

**Issue by huihuigogo** [iqbal-lab-org/clockwork#121]
Hi！
When I was running Clockwork, I had a question. 
I noticed that in the 'clockwork map_reads' step, the reads were mapped to the H37Rv reference genome, and then in the 'clockwork variant_call_one_sample' step, they were mapped  to the H37Rv reference genome again. Why are there two rounds of alignment? Why not directly use the mapped results from the 'clockwork map_reads' step?”
Thanks in advance for your help!

**Comment by martinghunt** [comment]
If you only run `clockwork variant_call_one_sample`, then it maps once and then variant calls. In which case there is no need to run `clockwork map_reads`. Not sure what the issue is?

**Comment by huihuigogo** [comment]
Thank you very much for your quick reply！
Your answer solved some of my questions, but if I follow the description on GitHub (https://github.com/iqbal-lab-org/clockwork/wiki/Walkthrough-scripts-only) and execute clockwork in 3 steps (`clockwork map_reads` , `clockwork remove_contam`, `clockwork variant_call_one_sample`), it might be a waste to map twice? In addition, I always thought that the input of `clockwork variant_call_one_sample` requires the output of the first two steps and cannot be used directly.

**Comment by martinghunt** [comment]
Oh, I see...

Decontamination is optional. It makes sense for MTb because contamination (eg NTMs) could pollute the variant calling. It's up to you whether to run it or not.

The input reads to `variant_call_one_sample` is nothing special, it just needs paired reads in FASTQ format. I've added a note at the top of that wiki page to say that remove contamination is optional.

With regards to mapping twice: the mapping in remove contamination is to a huge reference set that does include H37Rv. This is not the same as mapping to only H37Rv. There will be edge cases where a read or its mate could be mapped differently. So it is necessary to remap.

**Comment by martinghunt** [comment]
A read to could map to a sequence other than H37Rv when mapping to the  remove contamination reference. It could map to H37Rv when only mapping to H37Rv during variant calling.

**Comment by huihuigogo** [comment]
I understand, thank you for your answer！
