### ISSUE TITLE
Some questions about the *.decontam.counts.tsv ?

### ISSUE THREAD

**Issue by huihuigogo** [iqbal-lab-org/clockwork#122]
I use the 'Walkthrough: scripts only.' option (Version:0.11.3)，and I have some questions about the *.decontam.counts.tsv file. Taking ERR067664 as an example, I present my question.
The contents of ERR067664.decontam.counts.tsv are as follows.
![9f3a2547fa1ffca8340ece3f1e75554](https://github.com/iqbal-lab-org/clockwork/assets/122064667/4dd81901-d2f9-4803-b95d-70df1a478e26)

I used `samtools view -F 4 ERR067664.sam | grep NC_000962.3 | wc -l` to filter the unmapped reads in the ERR067664.sam. After filtering, the number of reads mapped to the H37Rv reference genome was 2207352, but ERR067664.decontam.counts.tsv shows 2206287. The difference between the two is 1065 reads. Is my statistical method correct? How is the number of TB reads in the tsv file obtained?

In addition, how to get the number of Reads_kept_after_remove_contam reads in the tsv file? Are Reads_kept_after_remove_contam reads used for `clockwork variant_call_one_sample`? I simply added the number of TB reads and the number of Unmapped reads, but it does not seem to be equal to the number of Reads_kept_after_remove_contam reads. Could you please help me?

Thanks in advance for your help!

**Comment by martinghunt** [comment]
Not sure right now why the difference of 1065. Clockwork just counts the number of reads matched to H37Rv, and that's what it reports in `TB`.

Your second question: this will be because of read pairs. If a read matches H37Rv, then the both reads of the pair are kept regardless of what the read's mate did (it could be unmapped or mapped to a contamination sequence). Either both reads of a pair are kept, or they are both removed. The surviving read pairs are what is written to the output fastq files - the total number of which will be the count in `Reads_kept_after_remove_contam`.

**Comment by huihuigogo** [comment]
Is my method of using  `samtools view -F 4 ERR067664.sam | grep NC_000962.3 | wc -l` to obtain the number of reads matched to H37Rv consistent with your method? Is there something wrong with my statistical method?

Regarding the second question, I understand, thank you for your answer！

**Comment by martinghunt** [comment]
`grep NC_000962.3` will be looking for `NC_000962.3` anywhere in the line, not just in column 3. This means it counts a read that is mapped to anything, if its mate is mapped to `NC_000962.3`.

Try `awk '$3=="NC_000962.3"'` instead of `grep NC_000962.3`

**Comment by huihuigogo** [comment]
After  `samtools view -F 4 ERR067664.sam | awk '$3=="NC_000962.3"' | wc -l `  is executed, the result is 2206287, which is consistent with the number of TB reads in the tsv file !
Thank you very much for your patient answer！
