### ISSUE TITLE
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit

### ISSUE THREAD

**Issue by lily616** [iqbal-lab-org/clockwork#91]
Hello, I have a question about running the clockwork, could you give me a suggestion?

The code as the following,

Singularity> nextflow run nextflow/variant_call.nf --ref_dir /tmp/singularity-3.8.0/refrence/ --reads_in1 /tmp/singularity-3.8.0/diyData/1.L350_BDMS190036238-1a_1.fq.clean.gz --reads_in2 /tmp/singularity-3.8.0/diyData/1.L350_BDMS190036238-1a_2.fq.clean.gz --output_dir result --sample_name sample
N E X T F L O W  ~  version 21.10.0
Pulling nextflow-io/nextflow ...
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit

I have confused me some time, I would grateful for you if you can help me, thank you.

**Comment by martinghunt** [comment]
You need to have nextflow installed, independently of the singularity container, so that `nextflow` is in your `$PATH`. ie running just the command `nextflow` works. Then run:

```
nextflow run nextflow/variant_call.nf \
    -with-singularity clockwork_container.img 
    ... etc
```
where you'll have to replace `clockwork_container.img` with the name that you used when making the container when running `singularity build`. And the full command as in the wiki page https://github.com/iqbal-lab-org/clockwork/wiki/Pipelines-without-a-database
